[package]
name = "rust_ato"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = "1.22.0"
serde-xml-rs = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
walkdir = "2"
error-stack = "0.1.1"