[package]
name = "rust_ato"
version = "0.1.0"
edition = "2018"

[dependencies]
rust_decimal = "1.22.0"
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.21", features = ["serialize"] }